### ISSUE TITLE
Error "Cannot read property 'props' of undefined"

### ISSUE THREAD

**Issue by SLyHuy** [mikefey/react-responsive-image#1]
![screen shot 2017-02-21 at 15 31 02](https://cloud.githubusercontent.com/assets/1643397/23156770/dc092024-f84a-11e6-8348-2ad542c02093.png)

Source code:
                   

```<div className="product _wrap-image">
                        <ResponsiveImage
                            className="product _image"
                            alt={self.props.product.name}
                        >
                            <ResponsiveImageSize
                                default
                                minWidth={0}
                                path={self.props.product.image}
                            />
                        </ResponsiveImage>```

**Comment by mikefey** [comment]
@SLyHuy I made a few changes and published a new release to NPM .
- Add a unit test for the `alt` prop
- Bind `this` to all functions in the `ResponsiveImage` component so it should always reference the component.

Could you update to the latest version and let me know if you still get this error? If so, it would be helpful to see the full source of your component, then I can try to help debug.

**Comment by SLyHuy** [comment]
@mikefey okay, I'll try, thanks.
