### ISSUE TITLE
Lazy loading feature needs trigger ? 

### ISSUE THREAD

**Issue by Nmuta** [mikefey/react-responsive-image#4]
I need some clarification on the lazy loading prop.  When I set the prop to true , the images stop loading all together.  Do I have to manually call the loadImage( ) method on my own?  Please advise. I do like using the component, super helpful.

**Comment by mikefey** [comment]
Yes, when the `lazy ` prop is set to `true` you do have to manually call the `loadImage` method. I realize this isn't really the "React" way of doing things, I've been meaning to refactor but haven't had a chance. I think making `loadImage` a prop that the loads the image when set to `true` would be the right way to go.

Glad you like using the component!

**Comment by Nmuta** [comment]
Thanks for the response, Mike !  So, since this is a dynamically changing component according to browser size, "when" and where exactly do you call loadImage( ) ?  I'm currently using this within a stateless functional component, should I switch over to using a traditional React component in order to get lifecycle hooks?

**Comment by Nmuta** [comment]
The quickest way is if you had an example showing how and where you're calling loadImage when lazy is set to true , if possible.  If not, just a description would work and again thank you. If you have a method to accept donations for the project also, let me know, thanks!

**Comment by mikefey** [comment]
Hi Nmuta,

I just refactored and released a new version, now `loadImage` is a prop on the `ResponsiveImage` component. So if `lazy` is set to `true`, the image will load whenever you then set `loadImage` to `true`. Here's a quick example where the image would load after two seconds:

```
class DemoApp extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      shouldLoadImage: false,
    };
  }

  componentDidMount() {
    setTimeout(() => {
      this.setState({ shouldLoadImage: true });
    }, 2000);
  }

  render() {
    return (
      <div>
        <ResponsiveImage
          lazy
          loadImage={this.state.shouldLoadImage}
        >
          <ResponsiveImageSize
            default
            minWidth={0}
            path={'initial-url.jpg'}
          />
          <ResponsiveImageSize
            minWidth={768}
            path={'medium-url.jpg'}
          />
          <ResponsiveImageSize
            minWidth={1100}
            path={'original-url.jpg'}
          />
        </ResponsiveImage>
      </div>
    );
  }
}
```

Hopefully that's helpful but let me know if you have any questions. No need for donations right now, the project hasn't taken too much time to maintain so far. I appreciate the thought though!
